apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: moon-route
  namespace: moon
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
  hostnames:
    - "moon.skdemo.online"
  rules:
    - backendRefs:
        - name: moon-service
          port: 80